djomodoro/djomodoro/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin

from tasks import urls as task_urls
from . import views

urlpatterns = patterns('',
    url(r'^$', views.IndexRedirect.as_view(), name='index'),
    url(r'^t/', include(task_urls, namespace="tasks")),
    url(r'^admin/', include(admin.site.urls)),
)

# In production static stuff should be server by http server
# static handles automatically
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Django debug toolbar stuff
# Handles static files
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

djomodoro/tasks/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^run/update/(?P<pk>\d+)$', views.UpdateRunView.as_view(),
        name="run_update"),
    url(r'^run/list$', views.RunListView.as_view(), name="run_list"),
    url(r'^task/create$', views.NewTaskView.as_view(), name="task_create"),
    url(r'^task/(?P<pk>\d+)$', views.TaskDetailView.as_view(),
        name="task_detail"),
)

djomodoro/tasks/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Task(models.Model):
    name = models.CharField(_("task name"), max_length=200, null=False)
    description = models.TextField(_("task description"), blank=True)
    # run_set

    def __str__(self):
        return self.name


class Run(models.Model):
    task = models.ForeignKey(Task)
    start = models.DateTimeField(_("Task start time"))
    finish = models.DateTimeField(_("Task finish time"), null=True)

    def clean(self):
        if self.finish and self.start > self.finish:
            raise ValidationError(
                {'finish': _('Finish time should be older than start time')}
            )

    def __str__(self):
        return "'{0}' task, '{1}' started, '{2}'' finished".format(self.task,
                                                                   self.start,
                                                                   self.finish)

djomodoro/djomodoro/views.py
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse_lazy


class IndexRedirect(RedirectView):
    def get_redirect_url(self):
        return reverse_lazy("tasks:index")

djomodoro/tasks/views.py
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Count
from django.http import JsonResponse
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext_lazy as _

from .models import Task, Run


# Custom mixins
class AjaxableResponseMixin(object):

    def form_invalid(self, form):
        response = super(AjaxableResponseMixin, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.is_ajax():
            data = {
                'pk': self.object.pk,
            }
            return JsonResponse(data)
        else:
            return response


class IndexView(AjaxableResponseMixin, CreateView):
    model = Run
    fields = ['task', 'start']
    template_name = "tasks/task_index.html"
    success_url = reverse_lazy("tasks:index")


class UpdateRunView(AjaxableResponseMixin, UpdateView):
    model = Run
    fields = ['task', 'start', 'finish']
    template_name = "tasks/task_index.html"

    def get_success_url(self):
        return reverse_lazy("tasks:run_update", kwargs=self.kwargs)


class RunListView(ListView):
    queryset = Run.objects.order_by('-id')
    template_name = "tasks/task_run_list.html"
    context_object_name = "run_list"
    paginate_by = 10


class NewTaskView(SuccessMessageMixin, CreateView):
    model = Task
    fields = ['name', 'description']
    template_name = "tasks/task_task_create.html"
    success_url = reverse_lazy("tasks:task_create")
    success_message = _("%(name)s was created successfully")

    def get_context_data(self, **kwargs):
        kwargs['task_list'] = Task.objects.annotate(
            Count('run')).order_by('-id')[:5]
        return super().get_context_data(**kwargs)  # Python3 style super


class TaskDetailView(DetailView):
    model = Task
    template_name = "tasks/task_task_detail.html"
    context_object_name = "task_object"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginate_by = self.__class__.paginate_by
        # Add our custom paginator
        page = int(self.request.GET.get('page', 1))

        run_list_count = Run.objects.filter(task_id=self.kwargs['pk']).count()
        context['run_list'] = Run.objects.filter(
            task_id=self.kwargs['pk'])[(page-1)*paginate_by:page*paginate_by]

        context['is_paginated'] = run_list_count > 0
        if context['is_paginated']:
            page_obj = {
                'has_previous': page > 1,
                'has_next': (run_list_count - (page * paginate_by)) > 0,
                'previous_page_number': page - 1,
                'next_page_number': page + 1,
            }
            context['page_obj'] = page_obj
        return context

djomodoro/templates/base.html
{# base.html #}
{% load pipeline %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% trans "Djomodoro your pomodoro tasker" %}</title>

    {% stylesheet 'libs' %}
    {% stylesheet 'djomodoro' %}
    {% javascript 'libs' %}
    {% block head %}
    {% endblock head %}
  </head>

  <body>
  {% block navbar %}
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'tasks:index' %}">Djomodoro</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'tasks:index' %}">{% trans "home" %}</a></li>
            <li><a href="{% url 'tasks:task_create' %}">{% trans "Tasks" %}</a></li>
            <li><a href="{% url 'tasks:run_list' %}">{% trans "History" %}</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    {% endblock navbar %}

    <div class="container">
    {% block container %}
    {% endblock container %}
    </div><!-- /.container -->
  </body>
</html>

djomodoro/templates/tasks/base_tasks.html
{# tasks/base_tasks #}
{% extends "base.html" %}

djomodoro/templates/tasks/task_index.html
{# tasks/task_index #}
{% extends "tasks/base_tasks.html" %}
{% load pipeline %}
{% load i18n %}


{% block head %}
  {% javascript 'djomodoro' %}
{% endblock head %}

{% block container %}

<div class="progress">
  <div id='progress-bar' class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
  </div>
</div>

<div class="row">
  <div class="col-md-2 col-md-offset-5">
    <form id="task-form" action="{% url 'tasks:index' %}" method="post">
        {% csrf_token %}
        <div class="fieldWrapper">
            {{ form.task.errors }}
            <div class="row">
              <div class="col-md-1">
                <label for="{{ form.task.id_for_label }}">{% trans "task" %}:</label>
              </div>
              <div class="col-md-1 col-md-offset-2">
              {{ form.task }}
              </div>
            </div>
        </div>
        <input type="hidden" name="start" />
        <input type="hidden" value="Submit" />
    </form>
  </div>

</div>

<div class="row">
  <div class="col-md-2 col-md-offset-5">
  <!-- Hardcoded url becasue ajax update-->
    <form id="task-form-update" action="/t/run/update" method="post">
        {% csrf_token %}
        <input type="hidden" name="task" />
        <input type="hidden" name="start" />
        <input type="hidden" name="finish" />
        <input type="hidden" value="Submit" />
    </form>
  </div>
</div>

  <br/>
<div class="row">
  <div class="col-md-1 col-md-offset-5">
    <button id="start-counter" type="button" class="btn btn-primary btn-lg">Start!</button>
  </div>
  <div class="col-md-1">
    <a type="button" class="btn btn-success btn-lg" href="{% url 'tasks:task_create' %}">{% trans "New task" %}</a>
  </div>
<div class="row">
  <div class="col-md-5 col-md-offset-2">
    <h1 id="clock" style="font-size: 2000%"></h1>
  </div>
</div>
</div>


<script type="text/javascript">


</script>
{% endblock container %}

djomodoro/templates/tasks/task_run_create.html
{# tasks/task_task_create #}
{% extends "tasks/base_tasks.html" %}
{% load i18n %}

{% block container %}
<div class="row">
  <div class="col-md-4 col-md-offset-4">
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
    <form action="{% url 'tasks:run_create' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit" />
    </form>
  </div>

  <div class="col-md-6 col-md-offset-3">
  <div> {% trans "Last created tasks" %}</div>
  <table class="table table-striped">
  <thead>
        <tr>
          <th>{% trans "Name" %}</th>
          <th>{% trans "Description" %}</th>
          <th>{% trans "Runs" %}</th>
        </tr>
      </thead>
      <tbody>
      {% for i in task_list %}
        <tr>
            <td>{{ i.name }}</td>
            <td>{{ i.description }}</td>
            <td>{{ i.run__count }}</td>
        </tr>
      {% endfor %}
      </tbody>
 </table>
 </div>
</div>

{% endblock container %}

djomodoro/templates/tasks/task_run_list.html
{# tasks/task_run_list #}
{% extends "tasks/base_tasks.html" %}
{% load i18n %}

is_paginated, page_obj, and paginator

{% block container %}

<h2>{% trans "Run history" %}</h2>

{% if run_list %}
    <table class="table table-striped">
    <thead>
        <tr>
          <th>#</th>
          <th>{% trans "Task name" %}</th>
          <th>{% trans "Start" %}</th>
          <th>{% trans "Finish" %}</th>
        </tr>
      </thead>
        {% for run in run_list %}
            <tr>
                <td>{{ run.id }}</td>
                <td>{{ run.task }}</td>
                <td>{{ run.start|date:"c" }}</td>
                <td>{{ run.finish|date:"c" }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>{% trans "No runs" %}</p>
{% endif %}
{% if is_paginated %}
    <nav>
      <ul class="pager">
        {% if page_obj.has_previous %}
            <li><a href="{% url "tasks:run_list" %}?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
        {% if page_obj.has_next %}
            <li><a href="{% url "tasks:run_list" %}?page={{ page_obj.next_page_number }}">next</a></li>
        {% endif %}
      </ul>
    </nav>
{% endif %}

{% endblock container %}

djomodoro/templates/tasks/task_task_create.html
{# tasks/task_task_create #}
{% extends "tasks/base_tasks.html" %}
{% load i18n %}

{% block container %}
<div class="row">
  <div class="col-md-4 col-md-offset-4">
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
    <form action="{% url 'tasks:task_create' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit" />
    </form>
  </div>

  <div class="col-md-6 col-md-offset-3">
  <div> {% trans "Last created tasks" %}</div>
  <table class="table table-striped">
  <thead>
        <tr>
          <th>{% trans "Name" %}</th>
          <th>{% trans "Description" %}</th>
          <th>{% trans "Runs" %}</th>
          <th>{% trans "Details" %}</th>
        </tr>
      </thead>
      <tbody>
      {% for i in task_list %}
        <tr>
            <td>{{ i.name }}</td>
            <td>{{ i.description }}</td>
            <td>{{ i.run__count }}</td>
            <td>
                <a href="{% url 'tasks:task_detail' i.id %}">
                <span class="glyphicon glyphicon-info-sign" aria-hidden="true">

                </span>
                </a>
            </td>
        </tr>
      {% endfor %}
      </tbody>
 </table>
 </div>
</div>

{% endblock container %}

djomodoro/templates/tasks/task_task_detail.html
{# tasks/task_task_detail #}
{% extends "tasks/base_tasks.html" %}
{% load i18n %}

is_paginated, page_obj, and paginator

{% block container %}

  <div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h1>{{ task_object.name }}</h1>
        <h4>{{ task_object.description }}</h4>
      <table class="table table-striped">
      <thead>
            <tr>
              <th>{% trans "Id" %}</th>
              <th>{% trans "Start" %}</th>
              <th>{% trans "Finish" %}</th>
            </tr>
          </thead>
          <tbody>
          {% for i in run_list %}
            <tr>
                <td>{{ i.id }}</td>
                <td>{{ i.start }}</td>
                <td>{{ i.finish }}</td>
            </tr>
          {% endfor %}
          </tbody>
     </table>
    </div>
  </div>
  {% if is_paginated %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <nav>
        <ul class="pager">
          {% if page_obj.has_previous %}
              <li><a href="{% url "tasks:task_detail" task_object.id %}?page={{ page_obj.previous_page_number }}">Previous</a></li>
          {% endif %}
          {% if page_obj.has_next %}
              <li><a href="{% url "tasks:task_detail" task_object.id %}?page={{ page_obj.next_page_number }}">next</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </div>
{% endif %}

{% endblock container %}